<?php
require_once('views/partials/head.php');
require_once('views/partials/nav.php');
require_once('views/partials/banner.php');
require_once('models/show_list.model.php');
require_once('views/partials/category.php');
require_once('views/partials/show_main.php');
require_once('views/partials/footer.php');
?>